#!/usr/bin/env bash
#This script will display 'to infinity and beyond' indefinitely, and display 'I am invincible!!!' when it receives a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
