#!/usr/bin/env bash
#This while loop will echo out the numbers 1-20, with a special message to accompany the number in the cases of 4, 9, and 17
i=1
while ((i <= 20))
do
        echo "$i"
	if ((i==4))||((i==9))||((i==17)); then
	case $i in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
	esac
	fi
	((i++))
done
