#!/usr/bin/env bash
#this loop will iterate on the numbers 1-20 and print them, if the number is 4, 9, or 17, then it will print an additionall phrase, depending on the case.
i=1
while (( i<=20 ))
do
    echo "$i"
    if (( i==4||i==9||i==17 )); then
	case $i in
	    4) echo "bad luck from China";;
	    9) echo "bad luck from Japan";;
	    17) echo "bad luck from Italy";;
	esac
    fi
    ((i++))
done
